Repository jentic/jentic-public-apis, pull requests merged in 2025-09, with the labels that each got.

#423 docs(ISSUE_TEMPLATE): explain vendor_name format
  .github/ISSUE_TEMPLATE/import-openapi-to-jentic-public-apis.md
Labels: documentation

#433 fix(ISSUE_TEMPLATE): remove backticks to avoid evalulation
  .github/ISSUE_TEMPLATE/import-openapi-to-jentic-public-apis.md
Labels: bug

#461 fix(apis): fix ElevenLabs OpenAPI Document
  apis/openapi/elevenlabs.io/main/1.0/feedback.json
  apis/openapi/elevenlabs.io/main/1.0/openapi.json
  apis/openapi/elevenlabs.io/main/1.0/overlay.json
Labels: bug

#415 Slack OpenAPI spec updates based on recent docs
  apis/openapi/slack.com/main/1.7.0/openapi.json
Labels: enhancement

#480 fix(apis): provide corrected Gmail OpenAPI 3.1.0 Document
  apis/openapi/googleapis.com/gmail/v1/openapi.json
  apis/openapi/googleapis.com/gmail/v1/overlay.json
Labels: enhancement
